# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RunKitDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RunKitDemo
  pod 'RunKit', :path => '../'

  target 'RunKitDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RunKitDemoUITests' do
    # Pods for testing
  end

end
